VINES/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VINES.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

VINES/Pages/CommunityPosts/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VINES.Models;

namespace VINES.Pages.CommunityPosts
{
    public class CreateModel : PageModel
    {
        private readonly DatabaseContext _Db;
        public List<CommunityPostCategoriesModel> categories { get; set; }
       

        public CreateModel(DatabaseContext Db)
        {
            _Db = Db;
            categories = _Db.CommunityPostCategories.ToList();
        }
        [BindProperty]
        public CommunityPost communityPost { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(string title, int catID, string content, int pID)
        {
            var posts = new Posts
            {
                isVisible = true
            };
            _Db.Post.Add(posts);
            await _Db.SaveChangesAsync();
            
            var communitypost = new CommunityPost
            {
                communityPostTitle = title,
                communityPostCategoryID = catID,
                communityPostContent = content,
                dateAdded = DateTime.Now,
                lastModified = DateTime.Now,
                postID = posts.postID
            };

            _Db.CommunityPosts.Add(communitypost);
           await _Db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

VINES/Pages/CommunityPosts/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VINES.Models;

namespace VINES.Pages.CommunityPosts
{
    
    public class EditModel : PageModel
    {
        private readonly DatabaseContext _context;
        public List<CommunityPostCategoriesModel> categories { get; set; }
        public EditModel(DatabaseContext context)
        {
            _context = context;
            
        }

        [BindProperty]
        public CommunityPost CommunityPost { get; set; } = default;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            categories = _context.CommunityPostCategories.ToList();
            if ((id == null || _context.CommunityPosts == null))
            {
                return NotFound();
            }

            var cp = await _context.CommunityPosts.FirstOrDefaultAsync(m => m.communityPostID == id);
            if (cp == null)
            {
                return NotFound();
            }

            CommunityPost = cp;
            return Page();

        }

        public async Task<IActionResult> OnPostAsync(int catID)
        {
            if (!ModelState.IsValid)
            {
                
                return Page();
            }

            _context.Attach(CommunityPost).State = EntityState.Modified;

            

            try
            {
                CommunityPost.communityPostCategoryID = catID;
                CommunityPost.lastModified = DateTime.Now;
                CommunityPost.dateAdded = DateTime.Now;

                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CommunityPostExists(CommunityPost.communityPostID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("Index");
        }
        private bool CommunityPostExists(int id)
        {
            return (_context.CommunityPosts?.Any(e => e.communityPostID == id)).GetValueOrDefault();
        }
    }
}

VINES/Pages/CommunityPosts/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using VINES.Models;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace VINES.Pages.CommunityPosts
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public List<CommunityPost> CommunityPosts { get; set; }
        public List<CommunityPostCategoriesModel> CommunityPostCategories { get; set; }

        private DatabaseContext db;

        public IndexModel(DatabaseContext _db)
        {
            db = _db;
        }

        public IActionResult OnGet()
        {
            var communityposts = db.CommunityPosts.ToList();
            return RedirectToPage("Index");
        }
    }
}

VINES/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace VINES.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VINES/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VINES.Models;
using VINES.Processes;

namespace VINES.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;




        [BindProperty(SupportsGet = true)]
        

        public List<CommunityPost> CommunityPosts { get; set; }
        public List<WebPages> WebPages { get; set; }
        public List<Vaccines> Vaccines { get; set; }
        public List<Diseases> Diseases { get; set; }
        public List<Institutions> Institutions { get; set; }


        //Ads
        [BindProperty]
        public List<Advertisement> ads { get; set; }
        public int rnd { get; set; }
        public Random rando =new Random(DateTime.Now.Millisecond);



        public List<Sources> Sources { get; set; }
        private DatabaseContext db;

        //pagination
        public int PageNo { get; set; }
        public bool ShowPrevious { get; set; }
        public bool ShowNext { get; set; }
        public int Count { get; set; }
        public int PageSize { get; set; }
        public int TotalPages { get; set; }

        public Help helper = new Help();


        public async Task<IActionResult> OnPostAd(int id)
        {
            Debug.WriteLine("hahaha "+ id);
            var ads = await db.advertisements.FindAsync(id);
            ads.clicks--;
            await db.SaveChangesAsync();
            return Redirect(ads.url);
        }


        public IndexModel(ILogger<IndexModel> logger, DatabaseContext _db)
        {
            _logger = logger;
            db = _db;
        }
        public void OnGet(int p = 1 , int s = 5)
        {
            string x = helper.Encrypt("test2022");
            Debug.Write("Encrypted = " + x);
            Debug.Write("Decrypted = " + helper.Decrypt(x));
            rando = new Random(DateTime.Now.Millisecond);
            try
            {
                ads = db.advertisements.Where(ad => ad.endDate > DateTime.UtcNow && ad.clicks > 0).ToList();
                if (ads.Count > 0)
                {
                    rnd = rando.Next(0, ads.Count - 1);
                }
                Debug.WriteLine(ads.Count + " ," + rnd);
            }
            catch (Exception ex) { }
            
            Sources = db.sources.ToList();
            CommunityPosts = db.CommunityPosts.ToList();
            WebPages = db.WebPages.OrderByDescending(webpage => webpage.uploadDate).Skip((p - 1) * s).Take(s).ToList();
            Count = db.WebPages.Count();
            PageSize = s;
            TotalPages = (int)Math.Ceiling(decimal.Divide(Count, PageSize));
            PageNo = p;
            ShowPrevious = (PageNo > 1) ? true : false;
            ShowNext = (PageNo < TotalPages) ? true : false;
            Vaccines = db.vaccines.Include("disease").ToList();
            Institutions = db.Institutions.ToList();
            Diseases = db.Diseases.ToList();
            Help help = new Help();
            Debug.WriteLine("test");
            help.checkIP();

            var rand = new Random();

        }

        
    }
}

VINES/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VINES.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

VINES/Pages/Subscribe.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Configuration;
using System.Threading.Tasks;
using System;
using VINES.Helper;
using Microsoft.Extensions.Configuration;
using System.Diagnostics;

namespace VINES.Pages
{
    public class SubscribeModel : PageModel
    {
        public IConfiguration configuration { get; }
        public SubscribeModel(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostCheckout(double total)
        {
            var payPalAPI = new PayPalAPI(configuration);
            string url = await payPalAPI.getRedirectURLToPayPal(total, "PHP");
            Debug.WriteLine(payPalAPI.paypalID);
            Debug.WriteLine(url);
            Console.WriteLine(total);
            return Redirect(url);
        }
    }
}

VINES/Pages/adminLanding.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VINES.Data;
using VINES.Models;
using VINES.Processes;

namespace VINES.Pages
{
    [Authorize("AdminOnly")]
    public class adminLandingModel : PageModel
    {
        public List<Vaccines> vaccines { get; set; }
        public List<Sources> Sources { get; set; }
        public List<Diseases> diseases { get; set; }
        public List<Diseases> disease { get; set; }
        public List<Institutions> institutions { get; set; }
        public List<InstitutionTypes> institutionTypes { get; set; }
        public List<Patients> patients { get; set; } 
        public List<Advertisers> advertisers { get; set; }

        public List<User> Users { get; set; }

        private DatabaseContext db;

        public adminLandingModel(DatabaseContext _db)
        {
            db = _db;
        }

       

        public void OnGet()
        {
            advertisers = db.advertisers.ToList();
            patients = db.Patients.ToList();
            vaccines = db.vaccines.ToList();
            diseases = db.diseases.ToList();
            institutions = db.Institutions.ToList();
            institutionTypes = db.InstitutionTypes.ToList();
            disease = db.Diseases.ToList();
            Sources = db.sources.ToList();
            Users = db.Users.ToList();

       
        }
       
    }
}

VINES/Pages/advertiserLanding.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using VINES.Helper;
using VINES.Models;
using VINES.Processes;

namespace VINES.Pages
{
    [Authorize("AdvertiserOnly")]
    public class advertiserLandingModel : PageModel
    {
        private IWebHostEnvironment _environment;
        public IConfiguration _configuration { get; }
        private readonly DatabaseContext _db;
        public advertiserLandingModel(IWebHostEnvironment environment, IConfiguration configuration, DatabaseContext db)
        {
            _environment = environment;
            _configuration = configuration;
            _db = db;
        }

        public List<AdvertisementType> AdTypes { get; set; }
        public List<Advertisement> Ads { get; set; }
        [BindProperty]
        public IFormFile Photo { get; set; }
        [BindProperty]
        public Advertisement Ad { get; set; }

        public List<AdReceipts> adr { get; set; }
        public List<Advertisement> active { get; set; }
        public List<Advertisement> inactive { get; set; }
        public List<Advertisement> advertisement { get; set; }

        public List<Advertisers> advertisers { get; set; }

        Help help = new Help();


        public async Task<IActionResult> OnPost()
        {
            string[] fileType = Photo.FileName.Split(".");
            int x = fileType.Length - 1;
            if (string.Equals(fileType[x], "jpg", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(fileType[x], "png", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(fileType[x], "jpeg", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(fileType[x], "gif", StringComparison.OrdinalIgnoreCase)
                )
            {


                string uploadsFolder = Path.Combine(_environment.WebRootPath, "images");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                Debug.WriteLine("file is in: " + filePath);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Photo.CopyToAsync(fileStream);
                }

                var aid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var uid = int.Parse(aid);
                var adver = _db.advertisers.Where(a => a.userID == uid).FirstOrDefault();

                Ad.imgsrc = uniqueFileName;
                Ad.advertiserID = adver.advertiserID;
                Ad.lastModified = DateTime.UtcNow;
                Ad.dateAdded = DateTime.UtcNow;
                Ad.clicks = 0;
                Ad.endDate = DateTime.UtcNow;
                _db.advertisements.Add(Ad);
                await _db.SaveChangesAsync();
                Debug.WriteLine("tama ka");
                ModelState.AddModelError("Success", "SUCCESS: You have now added your advertisement.");
            }
            else
            {
                ModelState.AddModelError("Error", "ERROR: Image must be .jpg/.jpeg/.png/.gif file.");
                Debug.WriteLine("bobo");
            }
            OnGet();
            return Page();
        }

        public async Task<IActionResult> OnPostCheckout(double total, int id)
        {
            var help = new Help();
            var adid = _db.advertisements.Find(id);
            var payPalAPI = new PayPalAPI(_configuration);
            string url = await payPalAPI.getRedirectURLToPayPal(total, "PHP");
            adid.textContent = help.Encrypt(payPalAPI.paypalID);
            _db.SaveChanges();
            Debug.WriteLine(url);
            Console.WriteLine(total);
            return Redirect(url);
        }


        public void OnGet()
        {
            var aid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var uid = int.Parse(aid);
            AdTypes = _db.advertisementTypes.ToList();
            Ads = _db.advertisements.Where(a => a.advertiser.userID == uid).ToList();
            adr = _db.AdReceipts.Where(a => a.advertiser.userID == uid).ToList();

            
            active = Ads.Where(a => a.endDate > DateTime.UtcNow && a.clicks > 0).ToList();
            inactive = Ads.Where(a => a.endDate <= DateTime.UtcNow || a.clicks <= 0).ToList();
            advertisement = _db.advertisements.ToList();
            advertisers = _db.advertisers.ToList();

            foreach(var x in adr)
            {
                x.paymentID = help.Decrypt(x.paymentID);
            }
            
        }
    }
}

VINES/Pages/testing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VINES.Pages
{
    public class testingModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

VINES/Pages/About.cshtml
@page
@{
    ViewData["Title"] = "About";
}


<!-- Favicons -->
<link href="~/assets/img/favicon.png" rel="icon">
<link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
<link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
<link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
<link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
<link href="~/assets/css/style1.css" rel="stylesheet">



<div class="blog-page area-padding">

    <div class="row">



        <center>
            <br />
            <h3>About VINES</h3>
            <br />
            <p>
                VINES (Vaccine Information and Educating System) is a web application that provides factual information regarding Vaccines.
            </p>
            <br />
            <h3>Our Mission:</h3>
            <br />
            <p>To provide relevant, factual and timely updates for information on Vaccines around Metro Manila. This is achieved by putting together news content from various public health and news departments from the Philippines with the ultimate goal of being able to create informed decisions with regards to vaccines.</p>
            <br />
            <h3>Services Offered:</h3>
            <br />
            <ul>
                <li><i class="bx bx-check-double"></i> Provide News and Updates regarding Vaccines.</li>
                <br />
                <li><i class="bx bx-check-double"></i> Generate lists of Institutions with your preferred Vaccines.</li>
                <br />
                <li><i class="bx bx-check-double"></i> Host Advertisements.</li>
                <br />
                <li><i class="bx bx-check-double"></i> View Institutions with specific Vaccines.</li>
            </ul>

        </center>
    </div>

</div>

VINES/Pages/CommunityPosts.cshtml
@page
@{
    ViewData["Title"] = "Community Posts";
}
<h1>@ViewData["Title"]</h1>

<p>Community posts.</p>

VINES/Pages/Contact.cshtml
@page
@{
    ViewData["Title"] = "Contact";
}
<br />
<br />
  <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact</h2>
          <p>Contact Us through these channels. Please allow 3 - 5 business days for a response.</p>
        </div>
        <div class="row mt-5">

          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>Metro Manila, Philippines</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>vinessystem@gmail.com</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Call:</h4>
                <p>09778252789</p>
              </div>

            </div>

          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

VINES/Pages/Subscribe.cshtml
@page
@model VINES.Pages.SubscribeModel

@{
    ViewData["Title"] = "Subscription";
}

<link href="~/assets/css/pricing.css" rel="stylesheet">
<center>
    <div class="container">
        <div class="align-center">

            <!-- ======= Pricing Section ======= -->
            <section id="pricing" class="pricing">
                <div class="container" data-aos="fade-up">

                    <div class="section-title">
                        <h2>Subscription</h2>
                        <p>Access advanced features available only for Subscribed members.</p>
                    </div>

                    <div class="row">
                        <center>
                            <div class="col-lg-4 col-md-12 mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="100">
                                <div class="box featured">
                                    <h3>Monthly</h3>
                                    <h4><sup>₱</sup>200<span> / month</span></h4>
                                    <ul>
                                        <li>News and Updates Regarding Vaccines</li>
                                        <li>ADS Shall Disappear</li>
                                        <li>Institutions based on Vaccine Preference</li>
                                        <li>Bookmarked News and Updates on Vaccines</li>
                                        <li>Community Posts and Comments</li>
                                    </ul>

                                    <div class="btn-wrap">
                                        <form asp-page-handler="checkout" method="post">
                                            <input type="hidden" name="total" value="200" />
                                            <button style="color:#001b66" class="btn-buy">Subscribe</button>

                                        </form>
                                    </div>
                                </div>
                            </div>

                        </center>

                    </div>

                </div>
            </section><!-- End Pricing Section -->

        </div>
    </div>

</center>

<!-- comment made -->

VINES/Pages/Subscription.cshtml
@page
@{
    ViewData["Title"] = "Subscription";
}

 <link href="~/assets/css/pricing.css" rel="stylesheet">
 <center>
 <div class="container">
     <div class="align-center">

    <!-- ======= Pricing Section ======= -->
    <section id="pricing" class="pricing">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Subscription</h2>
          <p>Access advanced features available only for Subscribed members.</p>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6" data-aos="zoom-im" data-aos-delay="100">
            <div class="box">
              <h3>Free</h3>
              <h4><sup>₱</sup>0<span> / month</span></h4>
              <ul>
                <li>News and Updates Regarding Vaccines</li>
                <li>View Instiitutions with COVID-19 Vaccines</li>
                <li>Annoying ADS</li>
                <li>Non Stop Annoying ADS</li>
                <li class="na">Institutions based on Vaccine Preference</li>
                <li class="na">Bookmarked News and Updates on Vaccines</li>
                <li class="na">Community Posts and Comments</li>
              </ul>
            </div>
          </div>
        

          <div class="col-lg-4 col-md-12 mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="100">
            <div class="box featured">
              <h3>Monthly</h3>
              <h4><sup>₱</sup>200<span> / month</span></h4>
              <ul>
                <li>News and Updates Regarding Vaccines</li>
                <li>ADS Shall Disappear</li>
                <li>Institutions based on Vaccine Preference</li>
                <li>Bookmarked News and Updates on Vaccines</li>
                <li>Community Posts and Comments</li>
              </ul>
              <div class="btn-wrap">
                <a href="#" class="btn-buy">Buy Now</a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mt-4 mt-lg-0" data-aos="zoom-in" data-aos-delay="100">
            <div class="box">
              <h3>Yearly</h3>
              <h4><sup>₱</sup>1299<span> / year</span></h4>
              <ul>
                <li>Save ₱1,100</li>
                <li>Get each Month at ₱109</li>
                <li>Hugs from Chris</li>
                <li>Hugs from John</li>
                <li>Hugs from Russ</li>
              </ul>
              <div class="btn-wrap">
                <a href="#" class="btn-buy">Buy Now</a>
              </div>
            </div>
          </div>
             
        </div>

      </div>
    </section><!-- End Pricing Section -->
    
     </div>
 </div>

  </center>

VINES/Pages/testing.cshtml
@page
@model VINES.Pages.testingModel
@{
}